import { TModifier } from './types'

export const SUCCESS_MODIFIER: TModifier = '--is-success'
export const DANGER_MODIFIER: TModifier = '--is-danger'
export const WARNING_MODIFIER: TModifier = '--is-warning'
export const INFO_MODIFIER: TModifier = '--is-info'
export const ACTIVE_MODIFIER: string = '--is-active'
export const DISABLED_MODIFIER: string = '--is-disabled'

export const HIDDEN_MODIFIER: string = 'helper--is-hidden'

export const COMPONENT_FIELD: string = 'field'
export const COMPONENT_PASSWORD_VISIBILITY: string = 'password-visibility'
export const COMPONENT_NOTIFICATION: string = 'notification'
export const COMPONENT_BUTTON: string = 'button'
export const COMPONENT_PANEL: string = 'panel'
export const COMPONENT_TABS: string = 'tabs'
export const COMPONENT_COLLAPSE: string = 'collapse'
export const COMPONENT_MODAL: string = 'modal'
export const COMPONENT_TOGGLE: string = 'toggle'
export const COMPONENT_LOADING: string = 'loading'
export const COMPONENT_SELECT: string = 'select'
export const COMPONENT_CAROUSEL: string = 'carousel'